### ISSUE TITLE
Internal server error for liking content

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#168]
https://github.com/healthlocker/healthlocker/issues/102#issuecomment-283391346

When clicking like on some content, there is an internal server error. ~This does not happen locally.~ This *does* happen locally, but in the same way as online in that some posts could be liked while some could not. I just happened to try on posts which worked.

When looking at `heroku logs --app healthlocker`, there is the following error:

```
2017-03-02T12:11:16.587139+00:00 app[web.1]: Request: POST /posts/7/likes
2017-03-02T12:11:16.587139+00:00 app[web.1]: ** (exit) an exception was raised:
2017-03-02T12:11:16.587140+00:00 app[web.1]:     ** (RuntimeError) you are attempting to change relation :likes of
2017-03-02T12:11:16.587141+00:00 app[web.1]: Healthlocker.Post, but there is missing data.
2017-03-02T12:11:16.587142+00:00 app[web.1]:
2017-03-02T12:11:16.587142+00:00 app[web.1]: If you are attempting to update an existing entry, please make sure
2017-03-02T12:11:16.587143+00:00 app[web.1]: you include the entry primary key (ID) alongside the data.
2017-03-02T12:11:16.587144+00:00 app[web.1]:
2017-03-02T12:11:16.587144+00:00 app[web.1]: If you have a relationship with many children, at least the same N
2017-03-02T12:11:16.587145+00:00 app[web.1]: children must be given on update. By default it is not possible to
2017-03-02T12:11:16.587146+00:00 app[web.1]: orphan embed nor associated records, attempting to do so results in
2017-03-02T12:11:16.587147+00:00 app[web.1]: this error message.
2017-03-02T12:11:16.587147+00:00 app[web.1]:
2017-03-02T12:11:16.587148+00:00 app[web.1]: If you don't desire the current behavior or if you are using embeds
2017-03-02T12:11:16.587148+00:00 app[web.1]: without a primary key, it is possible to change this behaviour by
2017-03-02T12:11:16.587149+00:00 app[web.1]: setting `:on_replace` when defining the relation. See `Ecto.Changeset`'s
2017-03-02T12:11:16.587150+00:00 app[web.1]: section on related data for more info.
2017-03-02T12:11:16.587150+00:00 app[web.1]:
2017-03-02T12:11:16.587151+00:00 app[web.1]:         (ecto) lib/ecto/changeset/relation.ex:176: Ecto.Changeset.Relation.on_replace/2
2017-03-02T12:11:16.587152+00:00 app[web.1]:         (ecto) lib/ecto/changeset/relation.ex:299: Ecto.Changeset.Relation.reduce_delete_changesets/5
2017-03-02T12:11:16.587153+00:00 app[web.1]:         (ecto) lib/ecto/changeset.ex:1083: Ecto.Changeset.put_relation/5
2017-03-02T12:11:16.587153+00:00 app[web.1]:         (healthlocker) web/controllers/post_controller.ex:45: Healthlocker.PostController.likes/2
2017-03-02T12:11:16.587154+00:00 app[web.1]:         (healthlocker) web/controllers/post_controller.ex:1: Healthlocker.PostController.action/2
2017-03-02T12:11:16.587155+00:00 app[web.1]:         (healthlocker) web/controllers/post_controller.ex:1: Healthlocker.PostController.phoenix_controller_pipeline/2
2017-03-02T12:11:16.587156+00:00 app[web.1]:         (healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.instrument/4
2017-03-02T12:11:16.587156+00:00 app[web.1]:         (healthlocker) lib/phoenix/router.ex:261: Healthlocker.Router.dispatch/2
```

It may be stemming from https://github.com/healthlocker/healthlocker/blob/master/web/controllers/post_controller.ex#L45, but requires further investigation.

**Comment by katbow** [comment]
I cleared the `posts_likes` table locally and it worked 😭 . 

Going to try setting `on_replace` as suggested in the error to prevent this from reoccurring.
