### ISSUE TITLE
PlugConnWrapperError happened in Healthlocker.ToolkitController#index

### ISSUE THREAD

**Issue by tonydaly** [healthlocker/healthlocker#425]
**Message**

```
  HTTP request error: ** (UndefinedFunctionError) function nil.id/0 is undefined or private
```

**Backtrace (last 10 lines)**

```
(healthlocker) web/controllers/toolkit_controller.ex:7: Healthlocker.ToolkitController.index/2
(healthlocker) web/controllers/toolkit_controller.ex:1: Healthlocker.ToolkitController.action/2
(healthlocker) web/controllers/toolkit_controller.ex:1: Healthlocker.ToolkitController.phoenix_controller_pipeline/2
(healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.instrument/4
(healthlocker) lib/phoenix/router.ex:261: Healthlocker.Router.dispatch/2
(healthlocker) web/router.ex:1: Healthlocker.Router.do_call/2
(healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.phoenix_pipeline/1
```

View on AppSignal: https://appsignal.com/healthlocker/sites/58ee002122139305bcd5267a/incidents/46

**Comment by tonydaly** [comment]
@katbow I think this is because we don't have `plug :authenticate` in the [ToolkitController](https://github.com/healthlocker/healthlocker/blob/master/web/controllers/toolkit_controller.ex). We should probably make this the default.

**Comment by katbow** [comment]
yeah I realised that when I saw this error. Forgot to add it in.
