### ISSUE TITLE
PlugConnWrapperError happened in Healthlocker.CareTeam.ContactController#show

### ISSUE THREAD

**Issue by tonydaly** [healthlocker/healthlocker#602]
**Message**

```
  HTTP request error: ** (MatchError) no match of right hand side value: []
```

**Backtrace (last 10 lines)**

```
(healthlocker) web/controllers/care_team/contact_controller.ex:19: Healthlocker.CareTeam.ContactController.service_user_for/1
(healthlocker) web/controllers/care_team/contact_controller.ex:8: Healthlocker.CareTeam.ContactController.show/2
(healthlocker) web/controllers/care_team/contact_controller.ex:1: Healthlocker.CareTeam.ContactController.action/2
(healthlocker) web/controllers/care_team/contact_controller.ex:1: Healthlocker.CareTeam.ContactController.phoenix_controller_pipeline/2
(healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.instrument/4
(healthlocker) lib/phoenix/router.ex:261: Healthlocker.Router.dispatch/2
(healthlocker) web/router.ex:1: Healthlocker.Router.do_call/2
(healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.phoenix_pipeline/1
```

View on AppSignal: https://appsignal.com/healthlocker/sites/58ee002122139305bcd5267a/incidents/64

**Comment by katbow** [comment]
This is the issue that's occurring when a clinician clicks on a carer in the caseload, correct?

**Comment by katbow** [comment]
I believe this is fixed now in an old pr? I'm not sure which though 😕

**Comment by markwilliamfirth** [comment]
@katbow found this old priority 1 in the backlog, can this be closed now?
