### ISSUE TITLE
DBConnection.ConnectionError

### ISSUE THREAD

**Issue by jruts** [healthlocker/healthlocker#80]
Whilst trying to install this application an error occurred on step `mix ecto.create`.

```
14:34:38.526 [error] GenServer #PID<0.194.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Healthlocker.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by jruts** [comment]
Apparently PostgreSQL need to be running locally. This might be worth mentioning in the installation steps.

**Comment by nelsonic** [comment]
Hi @jruts thanks _very_ much for taking the time to test the app.
We need to update the readme with instructions for downloading/installing PostgreSQL.
For now, see: https://github.com/dwyl/learn-postgresql#ubuntu

**Comment by jruts** [comment]
After installing postrges I get a `authentication` error. So this also needs to be updated in the readme.

```
** (Mix) The database for Healthlocker.Repo couldn't be created: FATAL 28P01 (invalid_password): password authentication failed for user "postgres"

14:41:57.695 [error] GenServer #PID<0.194.0> terminating
** (Postgrex.Error) FATAL 28P01 (invalid_password): password authentication failed for user "postgres"
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
```

**Comment by nelsonic** [comment]
@jruts thanks for sharing your progress/hurdles. 😍

**Comment by iteles** [comment]
@jruts I got the same thing yesterday and will be adding to the readme on this. Thanks for trying to install and opening the issue!

**Comment by katbow** [comment]
@Cleop here is the issue for the DB connection error you were getting 👍
